name: xpython (osx)

on:
  push:
    branches: [ python-2.4-to-2.7 ]
  pull_request:
    branches: [ python-2.4-to-2.7 ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macOS]
        python-version: [2.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install  -e .
        pip install -r requirements-dev.txt
    - name: Test xpython
      run: |
        make check
